import type { Offer } from "./types";

export const offers: Offer[] = [
  {
    name: "Bilan Essentiel",
    price: "79 EUR",
    description: "Une premiere base claire pour commencer serieusement.",
    highlight: "Ideal pour decouvrir l'approche Sabfit",
    benefits: [
      "Questionnaire objectif et habitudes",
      "Analyse de votre profil",
      "Programme musculation personnalise",
      "Conseils de mise en route",
    ],
    category: "unique",
  },
  {
    name: "Programme Corps & Nutrition",
    price: "149 EUR",
    previousPrice: "189 EUR",
    description: "La formule ideale pour repartir avec un cadre complet.",
    highlight: "Offre lancement la plus equilibree",
    benefits: [
      "Envoi de photos et analyse de votre profil",
      "Programme musculation personnalise",
      "Programme alimentaire structure",
      "Recommandations adaptees a votre quotidien",
    ],
    category: "unique",
    featured: true,
    badge: "Le plus choisi",
    ctaLabel: "Je veux cette formule",
  },
  {
    name: "Transformation Complete",
    price: "219 EUR",
    description: "Une formule plus poussee pour une strategie globale.",
    highlight: "Pour un cadre global plus pousse",
    benefits: [
      "Analyse complete de votre objectif",
      "Programme musculation personnalise",
      "Plan alimentaire personnalise",
      "Ajustement apres premier retour",
      "Vision plus complete de votre progression",
    ],
    category: "unique",
  },
  {
    name: "Suivi Start",
    price: "89 EUR / mois",
    description: "Pour avancer avec un cadre simple et evolutif.",
    highlight: "Le point d'entree le plus accessible",
    benefits: [
      "Programme musculation evolutif",
      "Cadre alimentaire simple",
      "1 point mensuel",
      "Support par mail",
    ],
    category: "subscription",
  },
  {
    name: "Suivi Progression",
    price: "149 EUR / mois",
    previousPrice: "179 EUR / mois",
    description: "L'equilibre ideal entre structure, suivi et progression.",
    highlight: "Offre lancement avec suivi WhatsApp",
    benefits: [
      "Programme musculation evolutif",
      "Nutrition adaptee a votre objectif",
      "Ajustements reguliers",
      "Suivi via WhatsApp",
      "Accompagnement plus complet",
    ],
    category: "subscription",
    featured: true,
    badge: "Formule signature",
    ctaLabel: "C'est celle qu'il me faut",
  },
  {
    name: "Coaching Premium",
    price: "229 EUR / mois",
    description: "Un accompagnement plus pousse, plus direct, plus prioritaire.",
    highlight: "Pour un accompagnement tres rapproche",
    benefits: [
      "Suivi complet",
      "Ajustements prioritaires",
      "Echanges plus rapproches",
      "Approche globale entrainement et alimentation",
      "Accompagnement premium",
    ],
    category: "subscription",
  },
];
